/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.DatosEditor.Asignaturas;

import data.DataProyecto;
import data.asignaturas.Asignatura;
import data.asignaturas.Carrera;
import data.asignaturas.Curso;
import data.asignaturas.Grupo;
import data.asignaturas.Tramo;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author David Gutiérrez Rubio <davidgutierrezrubio@gmail.com>
 */
public class JDlgAñadirAsignatura extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;
    private final Asignatura asigNueva;
    private final DataProyecto dataProyecto;
    private final boolean createNew;

    /**
     * Creates new form jDlgEditarAsignatura
     *
     * @param parent
     * @param modal
     * @param dataProyecto
     * @param asigEdit
     * @param createNew
     */
    public JDlgAñadirAsignatura(java.awt.Frame parent, boolean modal, DataProyecto dataProyecto, Asignatura asigEdit, boolean createNew) {
        super(parent, modal);
        initComponents();
        this.asigNueva = asigEdit;
        this.dataProyecto = dataProyecto;
        this.createNew = createNew;

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
        //Lleno los combos con la lista de carreras y cursos
        ArrayList<Carrera> estudiosCombo = dataProyecto.getDataAsignaturas().getCarreras();
        for (Carrera c : estudiosCombo) {
            jComboEstudios.addItem(c);
        }
        AutoCompleteDecorator.decorate(jComboEstudios);
        if (!estudiosCombo.isEmpty()) {
            jComboEstudios.setSelectedIndex(0);
        }

        rellenoComboCursos();
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                jTextNombreAsignatura.requestFocus();
            }
        });
    }

    /**
     *
     * @return
     */
    public JComboBox getjComboCursos() {
        return jComboCursos;
    }

    /**
     *
     * @return
     */
    public JComboBox getjComboEstudios() {
        return jComboEstudios;
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextNombreAsignatura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboCursos = new javax.swing.JComboBox();
        jComboEstudios = new javax.swing.JComboBox();
        jTextNombreCorto = new javax.swing.JTextField();
        jTextNumCreditos = new javax.swing.JTextField();
        jCheckCrearGrupos = new javax.swing.JCheckBox();
        jPanelOpcionesGrupos = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jSpinnerNumClases1 = new javax.swing.JSpinner();
        jSpinnerNumClases2 = new javax.swing.JSpinner();
        jSpinnerNumClases3 = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextDuracionClases3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextGrupos = new javax.swing.JTextField();
        jTextDuracionClases2 = new javax.swing.JTextField();
        jTextDuracionClases1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jLabel6.setText("clases de");

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText("Aceptar");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Créditos:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Curso:");

        jLabel4.setText("Estudios:");

        jCheckCrearGrupos.setText("Crear grupos automáticamente");
        jCheckCrearGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckCrearGruposActionPerformed(evt);
            }
        });

        jLabel13.setText("Grupos:");

        jSpinnerNumClases1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jSpinnerNumClases2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jSpinnerNumClases3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel11.setText("minutos cada una.");

        jLabel10.setText("clases de");

        jLabel9.setText("clases de");

        jTextDuracionClases3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel14.setText("Ej: A,B,C ");

        jTextGrupos.setToolTipText("Introduce los grupos separados por comas, por ejemplo: A,B,C,D");

        jTextDuracionClases2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextDuracionClases2.setText("90");

        jTextDuracionClases1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextDuracionClases1.setText("60");

        jLabel8.setText("minutos cada una, más");

        jLabel5.setText("La docencia semanal por grupo se distribuye en:");

        jLabel7.setText("minutos cada una, más");

        jLabel15.setText("clases de");

        javax.swing.GroupLayout jPanelOpcionesGruposLayout = new javax.swing.GroupLayout(jPanelOpcionesGrupos);
        jPanelOpcionesGrupos.setLayout(jPanelOpcionesGruposLayout);
        jPanelOpcionesGruposLayout.setHorizontalGroup(
            jPanelOpcionesGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesGruposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOpcionesGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOpcionesGruposLayout.createSequentialGroup()
                        .addComponent(jSpinnerNumClases1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addGap(10, 10, 10)
                        .addComponent(jTextDuracionClases1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7))
                    .addGroup(jPanelOpcionesGruposLayout.createSequentialGroup()
                        .addGroup(jPanelOpcionesGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOpcionesGruposLayout.createSequentialGroup()
                                .addComponent(jSpinnerNumClases2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanelOpcionesGruposLayout.createSequentialGroup()
                                .addComponent(jSpinnerNumClases3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addGap(16, 16, 16)))
                        .addGroup(jPanelOpcionesGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextDuracionClases3)
                            .addComponent(jTextDuracionClases2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelOpcionesGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)))
                    .addComponent(jLabel5)
                    .addGroup(jPanelOpcionesGruposLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelOpcionesGruposLayout.setVerticalGroup(
            jPanelOpcionesGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesGruposLayout.createSequentialGroup()
                .addGroup(jPanelOpcionesGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jTextGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(13, 13, 13)
                .addGroup(jPanelOpcionesGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerNumClases1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextDuracionClases1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelOpcionesGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerNumClases2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextDuracionClases2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelOpcionesGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerNumClases3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDuracionClases3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setText("Nombre corto:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelOpcionesGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelButton)
                        .addGap(18, 18, 18)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextNombreAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextNombreCorto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextNumCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckCrearGrupos))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextNombreAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextNombreCorto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextNumCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCheckCrearGrupos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelOpcionesGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton)))
        );

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void jCheckCrearGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckCrearGruposActionPerformed
        boolean enable = jCheckCrearGrupos.isSelected();
        for (Component c : jPanelOpcionesGrupos.getComponents()) {
            c.setEnabled(enable);
        }

    }//GEN-LAST:event_jCheckCrearGruposActionPerformed

    private void doClose(int retStatus) {
        if (retStatus == RET_OK) {
            asigNueva.setNombre(jTextNombreAsignatura.getText());
            asigNueva.setNombreCorto(jTextNombreCorto.getText());
            try {
                asigNueva.setNumCreditos(Integer.valueOf(jTextNumCreditos.getText()));
            } catch (NumberFormatException numberFormatException) {
            }
            Curso c = (Curso) jComboCursos.getSelectedItem();
            if (createNew) {
                dataProyecto.getDataAsignaturas().addAsignatura(c, asigNueva);
            }

//            asigNueva.removeAllGrupos();//Por si estoy editando una asignatura en vez de crear una nueva
            if ((jCheckCrearGrupos.isSelected()) && (!jTextGrupos.getText().isEmpty())) {
                String[] listaGrupos = jTextGrupos.getText().split(",");
                for (String nombreGrupo : listaGrupos) {
                    Grupo gr = new Grupo(nombreGrupo.trim());
                    addTramosToGrupo(gr);
                    asigNueva.addGrupo(gr);
                }
            }
        }

        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     *
     * @param gr
     */
    public void addTramosToGrupo(Grupo gr) {
        int numHoras, numClases;
        Tramo tr;
        try {
            numClases = Integer.valueOf(jSpinnerNumClases1.getValue().toString());
            numHoras = Integer.valueOf(jTextDuracionClases1.getText());
            for (int cont = 0; cont < numClases; cont++) {
                gr.addTramoGrupoCompleto(new Tramo(numHoras));
            }
        } catch (NumberFormatException numberFormatException) {
        }
        try {

            numClases = Integer.valueOf(jSpinnerNumClases2.getValue().toString());
            numHoras = Integer.valueOf(jTextDuracionClases2.getText());
            for (int cont = 0; cont < numClases; cont++) {
                gr.addTramoGrupoCompleto(new Tramo(numHoras));
            }
        } catch (NumberFormatException numberFormatException) {
        }

        try {
            numClases = Integer.valueOf(jSpinnerNumClases3.getValue().toString());
            numHoras = Integer.valueOf(jTextDuracionClases3.getText());
            for (int cont = 0; cont < numClases; cont++) {
                gr.addTramoGrupoCompleto(new Tramo(numHoras));
            }
        } catch (NumberFormatException numberFormatException) {
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox jCheckCrearGrupos;
    private javax.swing.JComboBox jComboCursos;
    private javax.swing.JComboBox jComboEstudios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelOpcionesGrupos;
    private javax.swing.JSpinner jSpinnerNumClases1;
    private javax.swing.JSpinner jSpinnerNumClases2;
    private javax.swing.JSpinner jSpinnerNumClases3;
    private javax.swing.JTextField jTextDuracionClases1;
    private javax.swing.JTextField jTextDuracionClases2;
    private javax.swing.JTextField jTextDuracionClases3;
    private javax.swing.JTextField jTextGrupos;
    private javax.swing.JTextField jTextNombreAsignatura;
    private javax.swing.JTextField jTextNombreCorto;
    private javax.swing.JTextField jTextNumCreditos;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = RET_CANCEL;

    private void rellenoComboCursos() {
        Object a = jComboEstudios.getSelectedItem();
        Carrera ac = (Carrera) a;
        if (ac != null) {
            jComboCursos.removeAllItems();
            ArrayList<Curso> cursosCombo = ac.getCursos();
            for (Curso c : cursosCombo) {
                jComboCursos.addItem(c);
            }
            AutoCompleteDecorator.decorate(jComboCursos);
            if (!cursosCombo.isEmpty()) {
                jComboCursos.setSelectedIndex(0);
            }
        }
    }

    /**
     *
     * @return
     */
    public JTextField getjTextDuracionClases1() {
        return jTextDuracionClases1;
    }

    /**
     *
     * @return
     */
    public JTextField getjTextDuracionClases2() {
        return jTextDuracionClases2;
    }

    /**
     *
     * @return
     */
    public JTextField getjTextDuracionClases3() {
        return jTextDuracionClases3;
    }

    /**
     *
     * @return
     */
    public JTextField getjTextGrupos() {
        return jTextGrupos;
    }

    /**
     *
     * @return
     */
    public JTextField getjTextNombreAsignatura() {
        return jTextNombreAsignatura;
    }

    /**
     *
     * @return
     */
    public JTextField getjTextNombreCorto() {
        return jTextNombreCorto;
    }
}
